
import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface props {
  children?:React.ReactNode;
}

export default function RootLayout(props:props) {
  return (
    
      <>{props.children}</>
   
  )
}
